# Generated by Django 2.1.3 on 2018-11-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='../static/defaults/default-user.png', upload_to=''),
        ),
    ]
