# Generated by Django 2.1.3 on 2018-11-02 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeCore', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Owner'},
        ),
        migrations.AlterModelOptions(
            name='veterinary',
            options={'verbose_name': 'Veterinary'},
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeCore.AnimalBrand'),
        ),
    ]
